Add hls-1.5.1 (incomplete)
haskell/ghcup-metadata pull request #11
Opened 2021-11-29 21:07 UTC by jneira

* The artifacts from https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/44521 should be copied in https://downloads.haskell.org/ghcup/unofficial-bindists/haskell-language-server/1.5.1/
  * is there someway to do it automatically? 
* The artifact for freebsd is missing as itfailed in the linked pipeline
* It still needs sha256sum for those artifacts

2021-11-29 21:12 UTC, hasufell commented
> The artifact for freebsd is missing as itfailed in the linked pipeline

That needs to be built manually then

> The artifacts from https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/44521 should be copied in https://downloads.haskell.org/ghcup/unofficial-bindists/haskell-language-server/1.5.1/

Why? They can be uploaded on the HLS release page

2021-11-29 21:17 UTC, hasufell commented
The yaml is invalid, the tests are failing

2021-11-29 21:24 UTC, jneira commented
> Why? They can be uploaded on the HLS release page

right, do you think that should be way to do it hereinafter? Asking to start to think automating it in gitlab scripts

> That needs to be built manually then

we could try to fix the build, at least to make it work for next releases, afaics it would need a ghcup fix:

```
curl --proto =https --tlsv1.2 -sSf https://get-ghcup.haskell.org
+ sh
Welcome to Haskell!
This script will download and install the following binaries:
  * ghcup - The Haskell toolchain installer
  * ghc   - The Glasgow Haskell Compiler
  * cabal - The Cabal build tool for managing Haskell software
  * stack - (optional) A cross-platform program for developing Haskell projects
  * hls   - (optional) A language server for developers to integrate with their editor/IDE
ghcup installs only into the following directory,
which can be removed anytime:
  /usr/home/vagrant/builds/0/haskell-haskell-language-server/FsB2Co4D/0/haskell/haskell-language-server/toolchain/.ghcup
13.0-RELEASE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
"curl -Lf https://downloads.haskell.org/~ghcup/0.1.17.4/x86_64-portbld-freebsd13-ghcup-0.1.17.4" failed!
```

I see https://downloads.haskell.org/ghcup/0.1.17.4/x86_64-freebsd12-ghcup-0.1.17.4  but no freebsd13, the more recent version with freebsd13 support is https://downloads.haskell.org/ghcup/0.1.17.2/

could be included freebsd13 in 0.1.17.4?

otoh i dont have a freebsd at hand right now 😉

2021-11-30 18:08 UTC, hasufell commented
> right, do you think that should be way to do it hereinafter? Asking to start to think automating it in gitlab scripts

did you upload them?

> we could try to fix the build, at least to make it work for next releases, afaics it would need a ghcup fix:

FreeBSD is irrelevant for now. We should build on 12.

2021-11-30 18:43 UTC, jneira commented
> > right, do you think that should be way to do it hereinafter? Asking to start to think automating it in gitlab scripts
> 
> did you upload them?

will do

> > we could try to fix the build, at least to make it work for next releases, afaics it would need a ghcup fix:
> 
> FreeBSD 13 is irrelevant for now. We should build on 12.

I've seen your pr https://github.com/haskell/haskell-language-server/pull/2420, thanks

2021-12-01 08:28 UTC, jneira commented
> will do

I am having problems wth my wifi connection and i was not able to download the artifacts from gitlab, the download stopped. :disappointed: 
To be sure the steps would be:

* download the arttifact as zip from https://gitlab.haskell.org/haskell/haskell-language-server/-/jobs/869452/artifacts/download
* repackage it as tar.gz
* compute the sha256sum
* upload to the github release
* change the sha256sums in the github release, adding the sha for the new artifact

2021-12-01 20:51 UTC, hasufell commented
the binaries are here: https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/44701

Now they have to tar'ed up properly and uploaded to the hls release page. Then this PR needs to be fixed.

2021-12-01 22:36 UTC, hasufell requested changes
There are missing binaries as described above

2021-12-02 06:04 UTC, jneira commented
sorry for the delay, a window update ruined my WiFi connection 2 days ago, it goes and comes but with weak signal, making impossible the download
I uninstalled it and it seems it has fixed the issue so will try asap

2021-12-02 08:52 UTC, jneira commented
@hasufell i've uploaded the binaries and updated sha256sums, could you take a quick look to confirm everything is ok with them? thanks!
https://github.com/haskell/haskell-language-server/releases/tag/1.5.1

2021-12-02 13:37 UTC, merged