vanilla: Add GHC 9.10.1
haskell/ghcup-metadata pull request #210
Opened 2024-05-10 21:49 UTC by bgamari

Workflow: https://github.com/haskell/ghcup-metadata/actions/runs/9038384303

2024-05-11 04:04 UTC, hasufell commented
There are unrelated commits in the PR, from HLS.

2024-05-12 16:22 UTC, hasufell requested changes

2024-05-12 16:22 UTC, hasufell commented on ghcup-vanilla-0.0.8.yaml
> +              dlUri: https://downloads.haskell.org/~ghc/9.10.1/ghc-9.10.1-x86_64-alpine3_12-linux.tar.xz
alpine-3.18 bindist is not used here

2024-05-12 16:22 UTC, hasufell commented on ghcup-vanilla-0.0.8.yaml
> +              dlUri: https://downloads.haskell.org/~ghc/9.10.1/ghc-9.10.1-x86_64-deb11-linux.tar.xz
Debian 12 bindist is not used here

2024-05-12 16:22 UTC, hasufell commented on ghcup-vanilla-0.0.8.yaml
> +              dlUri: https://downloads.haskell.org/~ghc/9.10.1/ghc-9.10.1-x86_64-fedora33-linux.tar.xz
Fedora 38 bindist is not used

2024-05-12 16:22 UTC, hasufell commented on ghcup-vanilla-0.0.8.yaml
> +              dlUri: https://downloads.haskell.org/~ghc/9.10.1/ghc-9.10.1-aarch64-deb10-linux.tar.xz
Probably needs a separate section for `Linux_Debian` supporting both deb10 and deb11 bindists.

2024-05-12 16:22 UTC, hasufell commented on ghcup-vanilla-0.0.8.yaml
> +      - Latest
In the vanilla channel `Recommended` and `Latest` usually goes together. Unless there's a reason not to?

2024-05-12 16:25 UTC, hasufell commented on ghcup-vanilla-0.0.8.yaml
> +          Linux_Mint:
we should probably also have an `unknown_versioning: *ghc-9101-x86_64-ubuntu20_04` here just in case `/etc/os-release` contains garbage or something.

2024-05-16 14:38 UTC, bgamari commented
Workflow: https://github.com/haskell/ghcup-metadata/actions/runs/9114189435

2024-05-16 14:39 UTC, bgamari commented
I believe this is ready, @maerwald.

Thanks for your review.

2024-05-17 17:52 UTC, merged